### ISSUE TITLE
Crash when loading prior output from file and then attempting to get next word

### ISSUE THREAD

**Issue by SneakyWhoami** [one19/markov-json#10]
```

  const Markov = require('markov-json');
  const quotes = new Markov('./json/author-markov.json');
  const author = new Markov('./json/author-markov.json');

/*
var q = require('./json/quotes.json');
var q2= require('./json/quotes2.json');
for (var p in q) {
        quotes.train(q[p].quote);
        author.train(q[p].name);
}
for (var p in q2) {
      quotes.train(q2[p].quoteText);
      author.train(q2[p].quoteAuthor);
}
*/

//quotes.output('./json/quotes-markov.json');
//author.output('./json/author-markov.json');

console.log(quotes.sentence(1));
console.log(author.words(2));
```
Hi and thanks for what is awesome so far.
Running the above doesn't go well. I can run it once and generate the chains. Then I can construct sentences with them or save them to files. But if I try to load them from files again I get issues:

```node_modules/markov-json/dist/src/index.js:141
            var randomSelection = Math.floor(memo[thisWord].sum * Math.random());
                                                           ^

TypeError: Cannot read property 'sum' of undefined
    at Markov.getNextWord (node_modules/markov-json/dist/src/index.js:141:60)
    at Markov.reconstruct (node_modules/markov-json/dist/src/index.js:97:38)
    at Markov.blob (node_modules/markov-json/dist/src/index.js:79:26)
    at Markov.words (node_modules/markov-json/dist/src/index.js:82:26)
    at Object.<anonymous> (index.js:22:20)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
```

Thanks again and nice work :-)

**Comment by one19** [comment]
Interesting!! I'll be taking a look at this asap! Thanks for bringing it up and the kind words!

I've found the issue. I forgot to memoize in the constructor when instantiating with an output json state or object.

I'll have a bugfix pr up in a hot second with this exact use case tested 😄

**Comment by one19** [comment]
markov-json 1.1.3 published 🎉

The test for the fix is here: https://github.com/one19/markov-json/pull/11/files#diff-9e5c9ec1f467dc8c8b19d27f7300efe0R74 Good catch!
